
# Initialize Rooms

level1 = Room.create(level: 1)
    level1.enemies.create(name: "slime")
level2 = Room.create(level: 2)
    level2.enemies.create(name: "slime")
    level2.enemies.create(name: "slime")
    level2.enemies.create(name: "slime")
level3 = Room.create(level: 3)
    level3.enemies.create(name: "slime")
    level3.enemies.create(name: "slime")
    level3.enemies.create(name: "slime")
    level3.enemies.create(name: "bat-black")
    level3.enemies.create(name: "bat-red")
level4 = Room.create(level: 4)
    level4.enemies.create(name: "slime")
    level4.enemies.create(name: "slime")
    level4.enemies.create(name: "slime")
    level4.enemies.create(name: "bat-black")
    level4.enemies.create(name: "bat-red")
    level4.enemies.create(name: "bat-black")
    level4.enemies.create(name: "bat-red")
level5 = Room.create(level: 5)
    level5.enemies.create(name: "zombie")
    level5.enemies.create(name: "zombie")
    level5.enemies.create(name: "zombie")
    level5.enemies.create(name: "zombie")
level6 = Room.create(level: 6)
    level6.enemies.create(name: "arachne")
    level6.enemies.create(name: "zombie")
    level6.enemies.create(name: "zombie")
    level6.enemies.create(name: "bat-black")
    level6.enemies.create(name: "bat-red")
level7 = Room.create(level: 7)
    level7.enemies.create(name: "arachne")
    level7.enemies.create(name: "arachne")
    level7.enemies.create(name: "zombie")
    level7.enemies.create(name: "bat-black")
    level7.enemies.create(name: "bat-red")
    level7.enemies.create(name: "slime")
    level7.enemies.create(name: "slime")
level8 = Room.create(level: 8)
    level8.enemies.create(name: "black-reaper")
    level8.enemies.create(name: "slime")
    level8.enemies.create(name: "slime")
    level8.enemies.create(name: "slime")
    level8.enemies.create(name: "slime")
level9 = Room.create(level: 9)
    level9.enemies.create(name: "golden-reaper")
    level9.enemies.create(name: "zombie")
    level9.enemies.create(name: "zombie")
    level9.enemies.create(name: "bat-black")
    level9.enemies.create(name: "bat-red")
    level9.enemies.create(name: "slime")
    level9.enemies.create(name: "slime")
level10 = Room.create(level: 10)
    level10.enemies.create(name: "black-reaper")
    level10.enemies.create(name: "golden-reaper")
    level10.enemies.create(name: "arachne")
    level10.enemies.create(name: "zombie")
    level10.enemies.create(name: "zombie")
    level10.enemies.create(name: "bat-black")
    level10.enemies.create(name: "bat-red")
    level10.enemies.create(name: "slime")
    level10.enemies.create(name: "slime")
    level10.enemies.create(name: "slime")
    level10.enemies.create(name: "slime")